name: CI

on: push
jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: python:3.12
    strategy:
      matrix:
        include:
          - name: "Unit tests"
            task: "pytest tests"
          - name: "Mypy type check"
            task: "mypy main/"
          - name: "Black formatting check"
            task: "black --diff --check main/"
          - name: "Isort check"
            task: "isort --check-only --diff main/"
          - name: "Flake8 linting"
            task: "flake8 main/"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: pip install --root-user-action=ignore  -r requirements.txt

      - name: Run ${{ matrix.name }}
        run: ${{ matrix.task }}
