name: CI

on: push
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    container:
      image: python:3.12
    strategy:
      matrix:
        include:
          - name: "Unit tests"
            task: "pytest tests"
          - name: "Mypy type check"
            task: "mypy --no-incremental --cache-dir=/dev/null ./main"
          - name: "Black formatting check"
            task: "black --diff --check main/"
          - name: "Isort check"
            task: "isort --profile=black --check-only --diff ./main"
          - name: "Flake8 linting"
            task: "flake8 ./main --max-line-length=88 --extend-ignore=E203,W503"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run ${{ matrix.name }}
        run: ${{ matrix.task }}
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519

      - name: Install deployment dependencies
        run: pip install fabric

      - name: Run deployment
        run: fab deploy
    environment: auto_deploy
